feat: added keycloak operator
linode/apl-core pull request #1625
Opened 2024-06-11 07:45 UTC by ElderMatt

This PR removed the keycloak job and replaces it with an operator.

2024-07-05 13:42 UTC, ferruhcihan approved these changes
LGTM

2024-07-08 08:28 UTC, j-zimnowoda commented on charts/apl-keycloak-operator/templates/deployment.yaml
> +          {{- if and .Values.configs (hasKey .Values.configs "tls") (hasKey .Values.configs.tls "certificates") }}
From the values.yaml file:
```
configs:
  tls: 
    certificates: {}
```

the path `configs.tls.certificates` seems to always exist. Wouldn't be better to check if the `certificates` is not an empty string?

2024-07-08 08:34 UTC, j-zimnowoda commented on charts/apl-keycloak-operator/templates/apl-keycloak-operator-tls-certs-cm.yaml
It is customary to name in just configmap.yaml if you have just a single cm

2024-07-08 08:35 UTC, j-zimnowoda commented on charts/apl-keycloak-operator/templates/rbac.yaml
> +- apiGroups: [""]
Do the operator need to read secrets from all namespaces?

2024-07-08 08:36 UTC, j-zimnowoda commented on charts/apl-keycloak-operator/templates/tests/test-connection.yaml
> +apiVersion: v1
operator is not a server thus connection does not need to be tested

2024-07-08 08:36 UTC, j-zimnowoda commented on charts/apl-keycloak-operator/values.yaml
> +service:
there is no service for the operator

2024-07-08 08:39 UTC, j-zimnowoda commented on values/apl-keycloak-operator/apl-keycloak-operator-raw.gotmpl
> +  - apiVersion: v1
The `custom-ca` does not seem to be used

2024-07-08 08:43 UTC, j-zimnowoda commented on charts/apl-keycloak-operator/templates/apl-keycloak-operator-tls-certs-cm.yaml
> +kind: ConfigMap
TLS certificates are usually stored in secrets not configmaps

2024-07-08 08:44 UTC, j-zimnowoda requested changes
Hi there few comments about the Helm chart

2024-07-09 10:02 UTC, j-zimnowoda approved these changes

2024-07-09 12:51 UTC, merged