fix: bucket only linode
linode/apl-core pull request #1703
Opened 2024-09-02 21:44 UTC by srodenhuis

Buckets can only be set when the OBJ provider is Linode. When using Minio, all buckets are pre-provisioned and bucket names can not be changed.

2024-09-03 12:38 UTC, j-zimnowoda commented
Is this PR have corresponding apl-api PR?

2024-09-03 12:48 UTC, j-zimnowoda commented on tests/fixtures/env/settings.yaml
> -    persistentVolumes:
please add migration

2024-09-03 12:49 UTC, j-zimnowoda commented on tests/fixtures/env/settings.yaml
> -    buckets:
please add migrations to values-changes.yaml

2024-09-03 12:51 UTC, j-zimnowoda requested changes
missing values migrations

2024-09-04 07:41 UTC, srodenhuis commented
corresponding PR for API: https://github.com/linode/apl-api/pull/546

2024-09-06 14:41 UTC, j-zimnowoda commented
Migration goes well
![image](https://github.com/user-attachments/assets/8d91f959-06e6-4b39-9ba3-00d0ea3326eb)
 but there is templating issue
 ```
  otomi:cmd:template:template:info # Templating STARTED +0ms
WARNING: release knative-serving-artifacts needs knative-operator, but knative-operator is not installed due to installed: false. Either mark knative-operator as installed or remove knative-operator from knative-serving-artifacts's needs
in helmfile.d/helmfile-04.databases.yaml: failed to render values files "../values/harbor/harbor-otomi-db.gotmpl": failed to render [../values/harbor/harbor-otomi-db.gotmpl], because of template: stringTemplate:25:34: executing "stringTemplate" at <$obj.linode.buckets.cnpg>: map has no entry for key "buckets"
  otomi:global:error Error: WARNING: release knative-serving-artifacts needs knative-operator, but knative-operator is not installed due to installed: false. Either mark knative-operator as installed or remove knative-operator from knative-serving-artifacts's needs
  otomi:global:error in helmfile.d/helmfile-04.databases.yaml: failed to render values files "../values/harbor/harbor-otomi-db.gotmpl": failed to render [../values/harbor/harbor-otomi-db.gotmpl], because of template: stringTemplate:25:34: executing "stringTemplate" at <$obj.linode.buckets.cnpg>: map has no entry for key "buckets"
  otomi:global:error     at hfCore (/Users/jzimnowo/workspace/linode/apl-core/src/common/hf.ts:55:17)
  otomi:global:error     exit code: 1
  otomi:global:error     at ChildProcess.<anonymous> (/Users/jzimnowo/workspace/linode/apl-core/node_modules/zx/dist/bundle.cjs:15261:22)
  otomi:global:error     at ChildProcess.emit (node:events:517:28)
  otomi:global:error     at ChildProcess.emit (node:domain:489:12)
  otomi:global:error     at maybeClose (node:internal/child_process:1098:16)
  otomi:global:error     at Socket.<anonymous> (node:internal/child_process:450:11)
  otomi:global:error     at Socket.emit (node:events:517:28)
  otomi:global:error     at Socket.emit (node:domain:489:12)
  otomi:global:error     at Pipe.<anonymous> (node:net:350:12) +0ms
# binzx/otomi template -l name=gitea-otomi-db
Starting inspector on 127.0.0.1:4320 failed: address already in use
  otomi:common:prepareEnvironment:info Checking environment +0ms
  otomi:common:crypt:decrypt:info Skipping decryption +0ms
  otomi:cmd:template:template:info # Templating STARTED +0ms
WARNING: release knative-serving-artifacts needs knative-operator, but knative-operator is not installed due to installed: false. Either mark knative-operator as installed or remove knative-operator from knative-serving-artifacts's needs
in helmfile.d/helmfile-04.databases.yaml: failed to render values files "../values/gitea/gitea-otomi-db.gotmpl": failed to render [../values/gitea/gitea-otomi-db.gotmpl], because of template: stringTemplate:26:34: executing "stringTemplate" at <$obj.linode.buckets.cnpg>: map has no entry for key "buckets"
  otomi:global:error Error: WARNING: release knative-serving-artifacts needs knative-operator, but knative-operator is not installed due to installed: false. Either mark knative-operator as installed or remove knative-operator from knative-serving-artifacts's needs
  otomi:global:error in helmfile.d/helmfile-04.databases.yaml: failed to render values files "../values/gitea/gitea-otomi-db.gotmpl": failed to render [../values/gitea/gitea-otomi-db.gotmpl], because of template: stringTemplate:26:34: executing "stringTemplate" at <$obj.linode.buckets.cnpg>: map has no entry for key "buckets"
  otomi:global:error     at hfCore (/Users/jzimnowo/workspace/linode/apl-core/src/common/hf.ts:55:17)
  otomi:global:error     exit code: 1
  otomi:global:error     at ChildProcess.<anonymous> (/Users/jzimnowo/workspace/linode/apl-core/node_modules/zx/dist/bundle.cjs:15261:22)
  otomi:global:error     at ChildProcess.emit (node:events:517:28)
  otomi:global:error     at ChildProcess.emit (node:domain:489:12)
  otomi:global:error     at maybeClose (node:internal/child_process:1098:16)
  otomi:global:error     at Socket.<anonymous> (node:internal/child_process:450:11)
  otomi:global:error     at Socket.emit (node:events:517:28)
  otomi:global:error     at Socket.emit (node:domain:489:12)
  otomi:global:error     at Pipe.<anonymous> (node:net:350:12) +0ms
  ```

2024-09-06 14:55 UTC, j-zimnowoda approved these changes
fixed dev cluster manually

2024-09-06 14:57 UTC, merged