Apl 248 gha update
linode/apl-core pull request #1748
Opened 2024-10-07 15:11 UTC by Ani1357

This PR updates our integration github actions to use valid domain names be default.
Key changes in this PR:
- removed Scaleway config
  -  deleted `.github/workflows/integration-on-schedule-dns-no-admin-pass.yml`
- removed Azure config
- Removed nip.io configs
  - removed `.github/workflows/integration-on-schedule-dns-no-admin-pass.yml`
  - removed `.github/workflows/integration-on-schedule-dns.yml`
  - updated nightly integration tests for `full`, `upgrade`, `minimal`, `minimal-with-teams` and `minimal-no-admin-pass`
- Set default `generate_password: yes`
- Set default `kms: age`
- Set default `certificate: letsencrypt_production`

### Testing:

- From [Deploy Otomi github action tab](https://github.com/linode/apl-core/actions/workflows/integration.yml) click **Run Workflow**.  
- In **Use workflow from** select **Branch: APL-248_gha-update**. 
- Select your **domain** and click **Deploy**. 
- After the deployment finishes you can download the kubeconfig and monitor the argocd applications status until they are ready.
- When ready you can access your cluster with the randomly generated password.

2024-10-10 07:43 UTC, j-zimnowoda commented on versions.yaml
> +api: APL-132-prometheus-ha
Could you revert versions ?

2024-10-10 07:50 UTC, Ani1357 commented on versions.yaml
> +api: APL-132-prometheus-ha
updated

2024-10-10 10:57 UTC, j-zimnowoda approved these changes
Tested with my domain. Works well

2024-10-10 11:03 UTC, ElderMatt requested changes
If this is possible it would be a nice change.

2024-10-10 12:12 UTC, j-zimnowoda commented on .github/workflows/integration.yml
> +          - select_your_domain_alias
wow, great idea!

2024-10-11 08:20 UTC, j-zimnowoda approved these changes

2024-10-14 08:00 UTC, ElderMatt approved these changes

2024-10-14 08:00 UTC, merged