feat: APL-281 adjusted resources for databases
linode/apl-core pull request #1856
Opened 2024-12-11 10:43 UTC by Ani1357

This PR updates the memory limits and request for  the platform apps cnpg databases in order to lower its footprint.
This PR also adds a migration in the values-changes in order to update the values for existing APL clusters.

2024-12-13 10:27 UTC, merll commented on helmfile.d/snippets/defaults.yaml
> +                memory: 64Mi
Would it not be better to set the requests equal with the limit, for increasing the QoS class (https://cloudnative-pg.io/documentation/1.24/resource_management/)?

2024-12-13 13:06 UTC, j-zimnowoda approved these changes
This change is a significant resource consumption reduction. Around ~2GB less memory required for each APL instance. The postgresql parameters seems to be reasonable

2024-12-13 13:16 UTC, CasLubbers requested changes

2024-12-13 13:16 UTC, CasLubbers commented on values-changes.yaml
> +    mutations:
These mutations are not same as the defaults is that correct?

2024-12-16 09:02 UTC, CasLubbers approved these changes

2024-12-16 10:50 UTC, merged