fix: rule expr for db backup prom rules
linode/apl-core pull request #1866
Opened 2024-12-12 20:13 UTC by srodenhuis

## Checklist

- [ ] Architecture Design Records have been added as `adr/*.md` and appended to list in `adr/_index.md`, if applicable.
- [ ] The `values-schema.yaml` file and `test/**` fixtures have been updated to reflect code changes, if applicable.
- [ ] The OpenApi Schema from redkubes/otomi-api project is compatible with definitions from `values-schema.yaml` file, if applicable.
- [ ] Helm releases are meeting otomi's baseline security policies, if applicable.
- [ ] Helm chart and helmfile changes are tested against upgrade scenario, if applicable.

2024-12-16 10:16 UTC, j-zimnowoda requested changes

2024-12-16 10:16 UTC, j-zimnowoda commented on values/prometheus-operator/rules/gitea-db-backup.yaml
> -        expr: time() - cnpg_collector_last_failed_backup_timestamp{namespace="gitea",pod=~"gitea-db-1"} > 86400 or time() - cnpg_collector_last_failed_backup_timestamp{namespace="gitea",pod=~"gitea-d
Unfortunately offset does not work if there are no metrics from last 24H, it seems this is a default setting for the platform. Moreover DB cluster can have more than two replicas and that expression would not cover that use case.
@Ani1357 and I are proposing the following expression:
```
(time() - max(cnpg_collector_last_available_backup_timestamp{namespace="gitea"}) > 24 * 60 * 60)
```

2024-12-17 14:08 UTC, j-zimnowoda approved these changes
![image](https://github.com/user-attachments/assets/868bbdb8-f08c-4254-b254-72a8db2292c3)

![image](https://github.com/user-attachments/assets/35c056ab-36f7-484f-a223-232e71dad5e9)

![image](https://github.com/user-attachments/assets/76025dd8-6b7a-45c2-8ce8-447c1d438d09)

2024-12-17 14:10 UTC, j-zimnowoda commented on values/prometheus-operator/rules/gitea-db-backup.yaml
> -        expr: time() - cnpg_collector_last_failed_backup_timestamp{namespace="gitea",pod=~"gitea-db-1"} > 86400 or time() - cnpg_collector_last_failed_backup_timestamp{namespace="gitea",pod=~"gitea-d
updated to the proposed solution

2024-12-17 14:15 UTC, Ani1357 approved these changes

2024-12-17 14:17 UTC, merged